# Generated by Django 5.1.2 on 2024-10-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField()),
                ('brand_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('genric', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255)),
                ('manufacturers', models.CharField(max_length=255)),
                ('package_container', models.CharField(max_length=255)),
                ('package_size', models.CharField(max_length=255)),
            ],
        ),
    ]
